### ISSUE TITLE
would the tts run locally in termux?

### ISSUE THREAD

**Issue by BarfingLemurs** [BentiGorlich/android-mimic3-tts-engine-wrapper#1]
If some packages can be install via a proot ubuntu environment, this could work nicely with llama.cpp for a realtime chat mobile experience!

**Comment by romanovj** [comment]
termux have:
termux-tts-engines
termux-tts-speak

**Comment by BentiGorlich** [comment]
What you could try is if docker can run inside of termux. Then you could host the mimic3 server via docker in termux. Then you could set the server address in the app to localhost. If that works I don't know. You could run into https problems with that as well, but it could work

**Comment by BarfingLemurs** [comment]
I'm not sure but I think running docker in termux requires root access. I tried running the linux installation script before from their site, ran into some issues, I'd like to be able to install the server manually though

**Comment by BentiGorlich** [comment]
As stated in the readme the main problem with that is that the onnxruntime is not supported by chaquope. So you could try to get that to work. I didn't have time yet to do that. I would very much like to run mimic3 locally too.

**Comment by romanovj** [comment]
I downloaded docker container with scopeo
unpacked with umoci
chroted into unpacked rootfs
repeated steps from Dockerfile
fixed mimic3_tts/voice.py

![Screenshot_20230926-230505_Termux](https://github.com/BentiGorlich/android-mimic3-tts-engine-wrapper/assets/105647092/69c64036-1137-4af9-a2c1-a5bcd04138f3)
![Screenshot_20230926-230517_Браузер](https://github.com/BentiGorlich/android-mimic3-tts-engine-wrapper/assets/105647092/c27c4e6e-61b2-42ef-a9dd-0028b2dec1af)

Lets see if I can proot into this rootfs. So far just root is enough. (Docker in termux requires custom kernel)

**Comment by romanovj** [comment]
no problems with proot and docker container isn't required (most likely)

just use debian 10 

```
apt-get install --yes --no-install-recommends \
        python3 python3-pip python3-venv \
        build-essential python3-dev
git clone https://github.com/MycroftAI/mimic3
cd mimic3
./install.sh
source .venv/bin/activate
python3 -m mimic3_http
```

**Comment by BarfingLemurs** [comment]
Debian 10 specifically, I see.. Used someone's install script since `proot-distro install debian-buster` is depreciated. Install script: https://github.com/sp4rkie/debian-on-termux

I get the server working, and with the latest app I get this is popup with 0.0.0.0 or localhost:

Clear text HTTP traffic to localhost not permitted. 



https://stackoverflow.com/questions/58022495/how-to-fix-cleartext-http-traffic-to-x-not-permitted

@BentiGorlich 
Could we enable this from the app?
~~Its probably specific to certain phones, I am testing on a pixel 6 xl, android 12~~

**Comment by BarfingLemurs** [comment]
So, the browser server does work with:

    pip install onnxruntime==1.15.1

do this to avoid these issues:

`socket.gaierror: [Errno -3] Temporary failure in name resolution `

Or

```
File "/root/mimic3/.venv/lib/python3.11/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 451, in _create_inference_session                              raise ValueError(              ValueError: This ORT build has ['AzureExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['AzureExecutionProvider', 'CPUExecutionProvider'], ...)
```

apk cannot link to server (yet!)

**Comment by BentiGorlich** [comment]
> Debian 10 specifically, I see.. Used someone's install script since `proot-distro install debian-buster` is depreciated. Install script: https://github.com/sp4rkie/debian-on-termux
> 
> I get the server working, and with the latest app I get this is popup with 0.0.0.0 or localhost:
> 
> Clear text HTTP traffic to localhost not permitted.
> 
> https://stackoverflow.com/questions/58022495/how-to-fix-cleartext-http-traffic-to-x-not-permitted
> 
> @BentiGorlich Could we enable this from the app? ~Its probably specific to certain phones, I am testing on a pixel 6 xl, android 12~

As I mentioned above:
>You could run into https problems with that as well, but it could work

I can try to enable it, but I would very much prefer the onnxruntime running on chaquopy, so this big workaround isn't needed....

**Comment by BentiGorlich** [comment]
I just pushed v0.1.2-alpha, I added a network config that should work. Can you test that?

**Comment by BarfingLemurs** [comment]
This works, just tested on v0.1.3. 

I can select a variety of voices within the app and notice the voice changes with librera pro's tts button (fdroid PDF reader) 

I had connection issues with low battery mode active.

It only seems to use one voice: <02/10/2023|21:42:07 INFO> Synthesizing text with http://0.0.0.0:59125/api/tts?ssml=0&audioTarget=client&noiseScale=0.726&noiseW=0.817&lengthScale=1.0&voice=en_UK%2Fapope_low : hi my name is

I can't select the other voices in system settings, or change pitch speed. For reference, I think you can control this systemwide in the app "espeak" from fdroid you click the gear icon beside (Text to speech output > Preferred engine)

But the default voice is very nice and fast enough.

**Comment by BentiGorlich** [comment]
Great that it worked :+1: 
The voice selection is a bit tricky, because the normal settings don't account for multiple different voices for a given language. I can't cheat that way eigher, so lets say I map the voices to a dialect, because only standardized locales are accepted by the system....

However the settings you select in the TTS app itself persist for the language selected. If the app that you use sends a request in the language you selected in the app, than that selected voice is used, however if the request is in a different language, than the first voice is used. Organic Maps for example lets you decide in which language the requests will be. Osmand just uses the system default and doesn't give you an option to change it.

If thats all a bit confusing, here's an example:
- your system default locale is engish
- you choose a english voice wihin the TTS Mimi3 Wrapper App
- every app that makes a request to the TTS service in english the voice you chose will be used to fullfill this request
- every app that makes a request in e.g. German will use the first voice in the list of German voices

**Comment by BarfingLemurs** [comment]
My system default is set to English (US)

When I use the tts in Organic Maps, and select Voice Language "Deutsch", I can only get the default UK english saying German words.

I pre-tested the m-ailabs-low > ramona deininger within the app, it should be the default,  it is the last voice I used.

Are you able to hear a different voice? Maybe it is something wrong with my system.

I can only hear a different voice eg: when I last used vtck (female voice) and have low battery mode on, and then I try tts and I hear "No connection" with the new voice.

**Comment by BentiGorlich** [comment]
When I set a German voice in "Mimic3 TTS Engine Wrapper"  and select English in Organic maps, then the voice I'll hear is the first one of the english voices. When I select German in Organic maps, then I hear the configured German voice....
If that is not how yours work, then thats definitely a bug

**Comment by BarfingLemurs** [comment]
great, thanks!

 I'll test the language issue on a fresh android device a bit later.
